# Pandas

Материалы:
* Макрушин С.В. "Лекция 2: Библиотека Pandas"
* https://pandas.pydata.org/docs/user_guide/index.html#
* https://pandas.pydata.org/docs/reference/index.html

## Разминка

In [1]:
import numpy as np
import pandas as pd

1. Загрузите данные из файла `sp500hst.txt` и обозначьте столбцы в соответствии с содержимым: `"date", "ticker", "open", "high", "low", "close", "volume"`.

In [8]:
sp = pd.read_csv(r"E:\Downloads\TOBD_2021_datasets\food_com\examples\sp500hst.txt", header=None)
sp.columns = ["date", "ticker", "open", "high", "low", "close", "volume"]
sp.head()

       date ticker   open     high     low  close  volume
0  20090821      A  25.60  25.6100  25.220  25.55   34758
1  20090824      A  25.64  25.7400  25.330  25.50   22247
2  20090825      A  25.50  25.7000  25.225  25.34   30891
3  20090826      A  25.32  25.6425  25.145  25.48   33334
4  20090827      A  25.50  25.5700  25.230  25.54   70176

2. Рассчитайте среднее значение показателей для каждого из столбцов c номерами 3-6.

In [9]:
sp.iloc[:, 3:].mean(axis=0)

high         43.102243
low          42.054464
close        42.601865
volume    81395.068138
dtype: float64

3. Добавьте столбец, содержащий только число месяца, к которому относится дата.

In [10]:
sp['date'] = pd.to_datetime(sp['date'], format='%Y%m%d')
sp['month'] = sp['date'].dt.month

4. Добавьте столбец с расшифровкой названия тикера, используя данные из файла `sp_data2.csv` . В случае нехватки данных об именах тикеров корректно обработать их.

In [15]:
ticker_name = pd.read_csv(r"E:\Downloads\TOBD_2021_datasets\food_com\examples\sp_data2.csv", sep=';', header=None)
ticker_name.columns = ['ticker', 'name', '%']
ticker_name.head(2)

  ticker        name     %
0   AAPL       Apple  3.6%
1   AMZN  Amazon.com  3.2%

In [17]:
sp.merge(ticker_name, how='left', left_on='ticker', right_on='ticker').tail(3)

             date ticker   open   high    low  close  volume  month name    %
122571 2010-08-17    ZMH  51.14  51.60  50.89  51.21   20498      8  NaN  NaN
122572 2010-08-19    ZMH  51.63  51.63  50.17  50.22   18259      8  NaN  NaN
122573 2010-08-20    ZMH  50.03  50.55  49.48  49.82   17792      8  NaN  NaN

## Лабораторная работа №2

In [2]:
import numpy as np
import pandas as pd

### Базовые операции с `DataFrame`

1.1 В файлах `recipes_short.csv` и `reviews_short.csv` находится информация об рецептах блюд и отзывах на эти рецепты соответственно. Загрузите данные из файлов в виде `pd.DataFrame` с названиями `recipes` и `reviews`. Обратите внимание на корректное считывание столбца(ов) с индексами.

In [5]:
recipes = pd.read_csv(r"E:\Downloads\TOBD_2021_datasets\food_com\data\recipes_short.csv")
reviews = pd.read_csv(r"E:\Downloads\TOBD_2021_datasets\food_com\data\reviews_short.csv", index_col=0)

In [8]:
recipes.head(2)

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN

In [9]:
reviews.head(2)

,user_id,recipe_id,date,rating,review
370476,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
624300,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...

1.2 Для каждой из таблиц выведите основные параметры:
    * количество точек данных (строк);
    * количество столбцов;
    * тип данных каждого столбца.

In [10]:
print(recipes.shape)
print(recipes.dtypes)

(30000, 8)
name               object
id                  int64
minutes             int64
contributor_id      int64
submitted          object
n_steps           float64
description        object
n_ingredients     float64
dtype: object

In [11]:
print(reviews.shape)
print(reviews.dtypes)

(126696, 5)
user_id       int64
recipe_id     int64
date         object
rating        int64
review       object
dtype: object

1.3 Исследуйте, в каких столбцах таблиц содержатся пропуски. Посчитайте долю строк, содержащих пропуски, в отношении к общему количеству строк.

In [15]:
recipes.isna().sum()

name                  0
id                    0
minutes               0
contributor_id        0
submitted             0
n_steps           11190
description         623
n_ingredients      8880
dtype: int64

In [16]:
recipes.isna().sum() / len(recipes)

name              0.000000
id                0.000000
minutes           0.000000
contributor_id    0.000000
submitted         0.000000
n_steps           0.373000
description       0.020767
n_ingredients     0.296000
dtype: float64

1.4 Рассчитайте среднее значение для каждого из числовых столбцов (где это имеет смысл).

In [17]:
recipes.mean(axis=0)

id                2.218793e+05
minutes           1.233581e+02
contributor_id    5.635901e+06
n_steps           9.805582e+00
n_ingredients     9.008286e+00
dtype: float64

1.5 Создайте серию из 10 случайных названий рецептов.

In [21]:
recipes['name'].sample(5)

29214                         whiskey pepper grilled steak
9919                 easy chicken or turkey with dumplings
22655                           roast beef sandwich spread
16627    lynn  easy chocolate   peanut butter  no bake ...
26554                                       swedish scones
Name: name, dtype: object

1.6 Измените индекс в таблице `reviews`, пронумеровав строки, начиная с нуля.

In [24]:
reviews.reset_index(drop=True)

,user_id,recipe_id,date,rating,review
0,21752,57993,2003-05-01,5,Last week whole sides of frozen salmon fillet ...
1,431813,142201,2007-09-16,5,So simple and so tasty! I used a yellow capsi...
2,400708,252013,2008-01-10,4,"Very nice breakfast HH, easy to make and yummy..."
3,2001852463,404716,2017-12-11,5,These are a favorite for the holidays and so e...
4,95810,129396,2008-03-14,5,Excellent soup! The tomato flavor is just gre...
...,...,...,...,...,...
126691,1270706,335534,2009-05-17,4,This recipe was great! I made it last night. I...
126692,2282344,8701,2012-06-03,0,This recipe is outstanding. I followed the rec...
126693,689540,222001,2008-04-08,5,"Well, we were not a crowd but it was a fabulou..."
126694,2000242659,354979,2015-06-02,5,I have been a steak eater and dedicated BBQ gr...
126695,463435,415599,2010-09-30,5,Wonderful and simple to prepare seasoning blen...

1.7 Выведите информацию о рецептах, время выполнения которых не больше 20 минут и кол-во ингредиентов в которых не больше 5.

In [31]:
recipes[(recipes['minutes']<=20) & (recipes['n_ingredients']<=5)].head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
28,quick biscuit bread,302399,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0
60,peas fit for a king or queen,303944,20,213909,2008-05-16,NaN,this recipe is so simple and the flavors are s...,5.0
90,hawaiian sunrise mimosa,100837,5,58104,2004-09-29,4.0,pineapple mimosa was changed to hawaiian sunri...,3.0
91,tasty dish s banana pudding in 2 minutes,286484,2,47892,2008-02-13,NaN,"""mmmm, i love bananas!"" a --tasty dish-- origi...",4.0
94,1 minute meatballs,11361,13,4470,2001-09-03,NaN,this is a real short cut for cooks in a hurry....,2.0

In [32]:
recipes.query('minutes <= 20 & n_ingredients <= 5').head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
28,quick biscuit bread,302399,20,213909,2008-05-06,11.0,this is a wonderful quick bread to make as an ...,5.0
60,peas fit for a king or queen,303944,20,213909,2008-05-16,NaN,this recipe is so simple and the flavors are s...,5.0
90,hawaiian sunrise mimosa,100837,5,58104,2004-09-29,4.0,pineapple mimosa was changed to hawaiian sunri...,3.0
91,tasty dish s banana pudding in 2 minutes,286484,2,47892,2008-02-13,NaN,"""mmmm, i love bananas!"" a --tasty dish-- origi...",4.0
94,1 minute meatballs,11361,13,4470,2001-09-03,NaN,this is a real short cut for cooks in a hurry....,2.0

### Работа с датами в `pandas`

2.1 Преобразуйте столбец `submitted` из таблицы `recipes` в формат времени. Модифицируйте решение задачи 1.1 так, чтобы считать столбец сразу в нужном формате.

In [34]:
recipes['submitted'] = pd.to_datetime(recipes['submitted'])
recipes.dtypes

name                      object
id                         int64
minutes                    int64
contributor_id             int64
submitted         datetime64[ns]
n_steps                  float64
description               object
n_ingredients            float64
dtype: object

In [35]:
recipes = pd.read_csv(r"E:\Downloads\TOBD_2021_datasets\food_com\data\recipes_short.csv", parse_dates=['submitted'])
recipes.dtypes

name                      object
id                         int64
minutes                    int64
contributor_id             int64
submitted         datetime64[ns]
n_steps                  float64
description               object
n_ingredients            float64
dtype: object

2.2 Выведите информацию о рецептах, добавленных в датасет не позже 2010 года.

In [36]:
recipes[recipes['submitted'].dt.year <= 2010]

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN
...,...,...,...,...,...,...,...,...
29993,zuni caf zucchini pickles,316950,2895,62264,2008-07-31,NaN,refrigerator pickles for some of the zucchini ...,8.0
29995,zurie s holey rustic olive and cheddar bread,267661,80,200862,2007-11-25,16.0,this is based on a french recipe but i changed...,10.0
29996,zwetschgenkuchen bavarian plum cake,386977,240,177443,2009-08-24,NaN,"this is a traditional fresh plum cake, thought...",11.0
29997,zwiebelkuchen southwest german onion cake,103312,75,161745,2004-11-03,NaN,this is a traditional late summer early fall s...,NaN
29999,cookies by design cookies on a stick,298512,29,506822,2008-04-15,9.0,"i've heard of the 'cookies by design' company,...",10.0

### Работа со строковыми данными в `pandas`

3.1  Добавьте в таблицу `recipes` столбец `description_length`, в котором хранится длина описания рецепта из столбца `description`.

In [38]:
recipes['description_length'] = recipes['description'].str.len()
recipes.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0

3.2 Измените название каждого рецепта в таблице `recipes` таким образом, чтобы каждое слово в названии начиналось с прописной буквы.

In [48]:
recipes['name'] = recipes['name'].str.title()
recipes.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length,name_word_count
0,George S At The Cove Black Bean Soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0,8
1,Healthy For Them Yogurt Popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0,5
2,I Can T Believe It S Spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0,7
3,Italian Gut Busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0,3
4,Love Is In The Air Beef Fondue Sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0,8

3.3 Добавьте в таблицу `recipes` столбец `name_word_count`, в котором хранится количество слов из названии рецепты (считайте, что слова в названии разделяются только пробелами).

In [46]:
recipes['name_word_count'] = recipes['name'].str.split(' ').map(lambda lst: [x for x in lst if x]).str.len()
recipes.head()

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length,name_word_count
0,george s at the cove black bean soup,44123,90,35193,2002-10-25,NaN,an original recipe created by chef scott meska...,18.0,330.0,8
1,healthy for them yogurt popsicles,67664,10,91970,2003-07-26,NaN,my children and their friends ask for my homem...,NaN,255.0,5
2,i can t believe it s spinach,38798,30,1533,2002-08-29,NaN,"these were so go, it surprised even me.",8.0,39.0,7
3,italian gut busters,35173,45,22724,2002-07-27,NaN,my sister-in-law made these for us at a family...,NaN,154.0,3
4,love is in the air beef fondue sauces,84797,25,4470,2004-02-23,4.0,i think a fondue is a very romantic casual din...,NaN,587.0,8

### Группировки таблиц `pd.DataFrame`

4.1 Посчитайте количество рецептов, представленных каждым из участников (`contributor_id`). Какой участник добавил максимальное кол-во рецептов?

In [60]:
recipes.groupby('contributor_id')['id'].count().sort_values()

contributor_id
302190      1
449247      1
449229      1
449014      1
448748      1
         ...
169430    183
1533      186
37779     345
37449     346
89831     421
Name: id, Length: 8404, dtype: int64

In [63]:
recipes.groupby('contributor_id')['id'].count().idxmax()

89831

4.2 Посчитайте средний рейтинг к каждому из рецептов. Для скольких рецептов отсутсвуют отзывы?

In [65]:
recipe_mean_rating = reviews.groupby('recipe_id')['rating'].mean()
recipe_mean_rating

recipe_id
48        1.000000
55        4.750000
66        4.944444
91        4.750000
94        5.000000
            ...
536547    5.000000
536610    0.000000
536728    4.000000
536729    4.750000
536747    0.000000
Name: rating, Length: 28100, dtype: float64

In [66]:
len(recipe_mean_rating), recipes['id'].nunique()

(28100, 30000)

4.3 Посчитайте количество рецептов с разбивкой по годам создания.

In [67]:
recipes.groupby(recipes['submitted'].dt.year)['id'].count()

submitted
1999     275
2000     104
2001     589
2002    2644
2003    2334
2004    2153
2005    3130
2006    3473
2007    4429
2008    4029
2009    2963
2010    1538
2011     922
2012     659
2013     490
2014     139
2015      42
2016      24
2017      39
2018      24
Name: id, dtype: int64

### Объединение таблиц `pd.DataFrame`

5.1 При помощи объединения таблиц, создайте `DataFrame`, состоящий из четырех столбцов: `id`, `name`, `user_id`, `rating`. Рецепты без отзывов должны отсутствовать в данной таблице. Подтвердите правильность работы вашего кода, выбрав рецепт, не имеющий отзывов, и выведя на экран строку из полученного `DataFrame`, содержащую информацию об этом отзыве.

In [76]:
no_reviews = recipes[~recipes['id'].isin(reviews['recipe_id'])]['id']
no_reviews[:5]

26    223349
29    342620
35    276594
49    216068
59    306590
Name: id, dtype: int64

In [104]:
res_5_1 = recipes.merge(reviews, left_on='id', right_on='recipe_id', how='inner')[['id', 'name', 'user_id', 'rating']]
res_5_1

            id                                    name  user_id  rating
0        44123   George S At The Cove  Black Bean Soup   743566       5
1        44123   George S At The Cove  Black Bean Soup    76503       5
2        44123   George S At The Cove  Black Bean Soup    34206       5
3        67664      Healthy For Them  Yogurt Popsicles   494084       5
4        67664      Healthy For Them  Yogurt Popsicles   303445       5
...        ...                                     ...      ...     ...
126691  486161                             Zydeco Soup   305531       5
126692  486161                             Zydeco Soup  1271506       5
126693  486161                             Zydeco Soup   724631       5
126694  486161                             Zydeco Soup   133174       5
126695  298512  Cookies By Design   Cookies On A Stick   804234       1

[126696 rows x 4 columns]

In [85]:
res.query('id==216068')

Empty DataFrame
Columns: [id, name, user_id, rating]
Index: []

5.2 При помощи объединения таблиц и группировок, создайте `DataFrame`, состоящий из трех столбцов: `recipe_id`, `name`, `review_count`. У рецептов, для которых отсутствуют отзывы, в соответствущем столбце должен быть указан 0. Подтвердите правильность работы вашего кода, выбрав рецепт, не имеющий отзывов, и выведя на экран строку из полученного `DataFrame`, содержащую информацию об этом отзыве.

In [105]:
review_count = reviews.groupby('recipe_id')['rating'].count().rename('review_count')
res_5_2 = recipes.merge(review_count, left_on='id', right_index=True, how='left')[['id', 'name', 'review_count']].fillna(0)
res_5_2

           id                                          name  review_count
0       44123         George S At The Cove  Black Bean Soup           3.0
1       67664            Healthy For Them  Yogurt Popsicles           8.0
2       38798                  I Can T Believe It S Spinach           3.0
3       35173                          Italian  Gut Busters           1.0
4       84797      Love Is In The Air  Beef Fondue   Sauces           8.0
...       ...                                           ...           ...
29995  267661  Zurie S Holey Rustic Olive And Cheddar Bread           4.0
29996  386977          Zwetschgenkuchen  Bavarian Plum Cake           2.0
29997  103312   Zwiebelkuchen   Southwest German Onion Cake           6.0
29998  486161                                   Zydeco Soup           6.0
29999  298512        Cookies By Design   Cookies On A Stick           1.0

[30000 rows x 3 columns]

In [95]:
res.query('id==216068')

        id                                     name  review_count
49  216068  Goulashy  Beef Stew For The Slow Cooker           0.0

5.3. Выясните, отзывы, добавленные в каком году, имеют наименьший средний рейтинг?

In [101]:
recipes_reviews = recipes.merge(reviews, left_on='id', right_on='recipe_id')
recipes_reviews.groupby(recipes_reviews['submitted'].dt.year)['rating'].mean().idxmin()

2017

### Сохранение таблиц `pd.DataFrame`

6.1 Отсортируйте таблицу в порядке убывания величины столбца `name_word_count` и сохраните результаты выполнения заданий 3.1-3.3 в csv файл.

In [103]:
recipes.sort_values(by='name_word_count', ascending=False).to_csv('')

,name,id,minutes,contributor_id,submitted,n_steps,description,n_ingredients,description_length,name_word_count
26223,Subru Uncle S Whole Green Moong Dal I Ll Be Ma...,77188,95,6357,2003-11-21,NaN,my dad and mom quite enjoy this lentil curry. ...,15.0,343.0,15
28083,Tsr Version Of T G I Friday S Black Bean Soup...,102274,75,74652,2004-10-19,9.0,from www.topsecretrecipes.com i got this copyc...,16.0,436.0,14
26222,Subru Uncle S Toor Ki Dal Sindhi Style Dad M...,76908,65,6357,2003-11-18,29.0,this is the lentil curry that subru uncle(our ...,15.0,1087.0,14
27876,Top Secret Recipes Version Of I H O P Griddl...,113346,20,175727,2005-03-14,5.0,this recipe is top secret recipes version of i...,9.0,129.0,14
5734,Chicken Curry Or Cat S Vomit On A Bed Of Magg...,294898,30,802799,2008-03-28,11.0,an old family recipe that's easy to make since...,12.0,144.0,13
...,...,...,...,...,...,...,...,...,...,...
3253,Blackmoons,323195,430,415934,2008-09-04,5.0,my mom was a newlywed in the 1950s when she fo...,NaN,389.0,1
4138,Bushwhacker,156521,10,177392,2006-02-17,1.0,this drink is an excellent after dinner drink ...,6.0,124.0,1
2357,Basbousa,12957,60,18391,2001-10-20,NaN,this is a traditional middle eastern dessert. ...,NaN,78.0,1
15052,Josefinas,264859,20,498271,2007-11-11,7.0,"from the junior league of corpus christi tx, t...",NaN,92.0,1
4710,Caramels,143615,30,212088,2005-11-02,NaN,i've been making these at christmas time for y...,6.0,341.0,1

6.2 Воспользовавшись `pd.ExcelWriter`, cохраните результаты 5.1 и 5.2 в файл: на лист с названием `Рецепты с оценками` сохраните результаты выполнения 5.1; на лист с названием `Количество отзывов по рецептам` сохраните результаты выполнения 5.2.

In [106]:
with pd.ExcelWriter('test.xlsx') as writer:
    res_5_1.to_excel(writer, sheet_name='Рецепты с оценками')
    res_5_2.to_excel(writer, sheet_name='Количество отзывов по рецептам')